### ISSUE TITLE
Can't convert to ilbc?

### ISSUE THREAD

**Issue by caojianhua** [soulfly/AudioIOService#1]
How to set the macro `qbBufferFrameSize` when use ilbc encode function.

By default inputBlock will give me 256 bytes, but one ilbc packet need 240 pcm packet at least.

**Comment by soulfly** [comment]
It doesn't work as is?

**Comment by caojianhua** [comment]
Yes,  `encodePCMtoiLBC` will return an AudioBuffer which the mDataByteSize will only be 1, if I input the AudioBuffer contain 256bytes PCM data (8000Hz, 1 channels).

As far as I know the iLBC encode must input an audio buffer contained 240 PCM packets.

**Comment by soulfly** [comment]
yes, 240 or 480

**Comment by caojianhua** [comment]
I'm writing some code to cumulative the PCM data use `TPCircularBuffer`, hope this is helpful.

Or how to config the `qbBufferFrameSize`?  I found the logic ignore the data when increase the value to 480.

```
if (inNumberFrames != normalFrameNumbers) {
            return noErr;
        }
```
